project_id: '467072'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
  # JSON translation files
  {
    source: '/i18n/en/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%',
  },
]
