project_id: '467072'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
  # JSON translation files
  {
    source: '/i18n/en/**/*',
    translation: '/i18n/%two_letters_code%/**/%original_file_name%',
  },
  # Docs Markdown files
  #{
  # source: '/docs/**/*',
  # translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-docs/current/**/%original_file_name%',
  #},
  # Tutorials Markdown files
  {
    source: '/tutorials/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-tutorials/**/%original_file_name%',
  },
  # Ecosystem Markdown files
  {
    source: '/media/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-media/**/%original_file_name%',
  },
  # CWPLUS Markdown files
  {
    source: '/cw-plus/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-cw-plus/**/%original_file_name%',
  },
  # Dev Academy Markdown files
  {
    source: '/dev-academy/**/*',
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-dev-academy/current/**/%original_file_name%',
  },
]
