module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    // community: [
    //   {
    //     type: 'autogenerated',
    //     dirName: '.',
    //   }],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
      {
        id: 'overview',
        type: 'doc',
        label: 'Overview',
      },
      {
        type: 'link',
        label: 'Job Listing',
        href: '/ecosystem/jobs',
      },
      {
        type: 'category',
        label: 'Testnets',
        collapsible: true,
        collapsed: true,
        items: [
          'testnets/build-requirements',
          'testnets/testnets',
        ]
      },
      {
        id: 'hall-of-fame',
        type: 'doc',
        label: 'Hall of Fame',
      },
      {
        type: 'category',
        label: 'Media',
        collapsible: true,
        collapsed: true,
        items: [
          'media/assets',
        ]
      },
  ],
  
};
