module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
     community: [
       {
         type: 'autogenerated',
         dirName: '.',
       }],

  // But you can create a sidebar manually
  
  
};
